# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-10 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20191110_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043e\u0442\u0432\u0435\u0442\u0430'),
            preserve_default=False,
        ),
    ]
