# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-14 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_answer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=False, verbose_name='\u0418\u0433\u0440\u0430 \u0434\u043e\u0441\u0442\u0443\u043f\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u041c\u0430\u043a\u0441\u0438\u043c\u0430\u043b\u044c\u043d\u043e\u0435 \u043a\u043e\u043b-\u0432\u043e \u0438\u0433\u0440\u043e\u043a\u043e\u0432'),
        ),
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u041c\u0438\u043d\u0438\u043c\u0430\u043b\u044c\u043d\u043e\u0435 \u043a\u043e\u043b-\u0432\u043e \u0438\u0433\u0440\u043e\u043a\u043e\u0432'),
        ),
    ]
