# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-08 08:27
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0004_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('content', ckeditor.fields.RichTextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('starts_at', models.DateTimeField(verbose_name='\u0412\u0440\u0435\u043c\u044f \u043d\u0430\u0447\u0430\u043b\u0430')),
                ('finished', models.BooleanField(default=False, verbose_name='\u0417\u0430\u043a\u043e\u043d\u0447\u0435\u043d')),
                ('status', models.CharField(choices=[[b'not_started', '\u041d\u0435 \u043d\u0430\u0447\u0430\u0442'], [b'started', '\u0418\u0434\u0435\u0442'], [b'scoring', '\u041f\u043e\u0434\u0441\u0447\u0435\u0442 \u043e\u0447\u043a\u043e\u0432'], [b'finished', '\u0417\u0430\u043a\u043e\u043d\u0447\u0435\u043d']], default=b'not_started', max_length=20, verbose_name='\u0421\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440 \u0438\u0433\u0440\u044b')),
            ],
            options={
                'ordering': ['starts_at'],
                'verbose_name': '\u0418\u0433\u0440\u0430',
                'verbose_name_plural': '\u0418\u0433\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='PlayerInGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='system.Game', verbose_name='\u0418\u0433\u0440\u0430')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Team', verbose_name='\u0412 \u0441\u043e\u0441\u0442\u0430\u0432\u0435 \u043a\u043e\u043c\u0430\u043d\u0434\u044b')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='\u0418\u0433\u0440\u043e\u043a')),
            ],
            options={
                'verbose_name': '\u0418\u0433\u0440\u043e\u043a \u0432 \u0438\u0433\u0440\u0435',
                'verbose_name_plural': '\u0418\u0433\u0440\u043e\u043a\u0438 \u0432 \u0438\u0433\u0440\u0435',
            },
        ),
        migrations.CreateModel(
            name='TeamInGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='system.Game', verbose_name='\u0418\u0433\u0440\u0430')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='system.Team', verbose_name='\u041a\u043e\u043c\u0430\u043d\u0434\u0430')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043c\u0430\u043d\u0434\u0430 \u0432 \u0438\u0433\u0440\u0435',
                'verbose_name_plural': '\u041a\u043e\u043c\u0430\u043d\u0434\u044b \u0432 \u0438\u0433\u0440\u0435',
            },
        ),
        migrations.AlterField(
            model_name='invitation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='system.Team', verbose_name='\u0412 \u043a\u043e\u043c\u0430\u043d\u0434\u0443'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u043e\u0433\u043e'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='system.Team', verbose_name='\u0422\u0435\u043a\u0443\u0449\u0430\u044f \u043a\u043e\u043c\u0430\u043d\u0434\u0430'),
        ),
    ]
