# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-08 12:25
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20191108_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0431\u043e\u043d\u0443\u0441\u0430')),
                ('content', ckeditor.fields.RichTextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0437\u0430\u0434\u0430\u043d\u0438\u044f \u0431\u043e\u043d\u0443\u0441\u0430')),
                ('bonus_time', models.IntegerField(default=0, verbose_name='\u0411\u043e\u043d\u0443\u0441\u043d\u043e\u0435 \u0432\u0440\u0435\u043c\u044f(\u043c\u0438\u043d)')),
                ('right_answers', models.TextField(verbose_name='\u041f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u044b\u0435 \u043e\u0442\u0432\u0435\u0442\u044b(json array)')),
            ],
            options={
                'ordering': ['level', 'order'],
                'verbose_name': '\u0411\u043e\u043d\u0443\u0441',
                'verbose_name_plural': '\u0411\u043e\u043d\u0443\u0441\u044b',
            },
        ),
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0443\u0440\u043e\u0432\u043d\u044f')),
                ('content', ckeditor.fields.RichTextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0437\u0430\u0434\u0430\u043d\u0438\u044f')),
                ('right_answers', models.TextField(verbose_name='\u041f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u044b\u0435 \u043e\u0442\u0432\u0435\u0442\u044b(json array)')),
                ('auto_close_time', models.IntegerField(default=0, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0430\u0432\u0442\u043e\u043f\u0435\u0440\u0435\u0445\u043e\u0434\u0430(\u043c\u0438\u043d)')),
            ],
            options={
                'ordering': ['game', 'order'],
                'verbose_name': '\u0423\u0440\u043e\u0432\u0435\u043d\u044c \u0438\u0433\u0440\u044b',
                'verbose_name_plural': '\u0423\u0440\u043e\u0432\u043d\u0438 \u0438\u0433\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0438')),
                ('available_in', models.IntegerField(default=0, verbose_name='\u0427\u0435\u0440\u0435\u0437 \u043a\u0430\u043a\u043e\u0435 \u0432\u0440\u0435\u043c\u044f \u043d\u0430 \u0443\u0440\u043e\u0432\u043d\u0435 \u043f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0430 \u0431\u0443\u0434\u0435\u0442 \u0434\u043e\u0441\u0442\u0443\u043f\u043d\u0430(\u043c\u0438\u043d)')),
                ('penalty', models.IntegerField(default=0, verbose_name='\u0428\u0442\u0440\u0430\u0444\u043d\u043e\u0435 \u0432\u0440\u0435\u043c\u044f(\u043c\u0438\u043d)')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.GameLevel', verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c \u0438\u0433\u0440\u044b')),
            ],
            options={
                'ordering': ['level', 'available_in'],
                'verbose_name': '\u041f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0430',
                'verbose_name_plural': '\u041f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0438',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='sequence',
            field=models.CharField(choices=[[b'linear', '\u041b\u0438\u043d\u0435\u0439\u043d\u0430\u044f'], [b'random', '\u0428\u0442\u0443\u0440\u043c\u043e\u0432\u0430\u044f']], default=b'linear', max_length=20, verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043e\u0432\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='game',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_games', to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440 \u0438\u0433\u0440\u044b'),
        ),
        migrations.AddField(
            model_name='gamelevel',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Game', verbose_name='\u0418\u0433\u0440\u044b'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.GameLevel', verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c \u0438\u0433\u0440\u044b'),
        ),
    ]
