# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-09 08:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0006_auto_20191108_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000, verbose_name='\u041e\u0442\u0432\u0435\u0442')),
                ('right', models.BooleanField(default=False, verbose_name='\u041f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u044b\u0439')),
                ('bonus_time', models.IntegerField(default=0, verbose_name='\u0411\u043e\u043d\u0443\u0441(\u0441\u0435\u043a)')),
            ],
            options={
                'verbose_name': '\u041e\u0442\u0432\u0435\u0442',
                'verbose_name_plural': '\u041e\u0442\u0432\u0435\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='LevelStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043d\u0430\u0447\u0430\u043b\u0430 \u0443\u0440\u043e\u0432\u043d\u044f')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043a\u043e\u043d\u0446\u0430 \u0443\u0440\u043e\u0432\u043d\u044f')),
                ('time_in_level', models.IntegerField(default=0, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043d\u0430 \u0443\u0440\u043e\u0432\u043d\u0435(\u0441\u0435\u043a)')),
                ('total_penalty', models.IntegerField(default=0, verbose_name='\u0428\u0442\u0440\u0430\u0444\u043e\u0432 \u043d\u0430 \u0443\u0440\u043e\u0432\u043d\u0435(\u0441\u0435\u043a)')),
                ('total_bonus', models.IntegerField(default=0, verbose_name='\u0411\u043e\u043d\u0443\u0441\u043e\u0432 \u043d\u0430 \u0443\u0440\u043e\u0432\u043d\u0435(\u0441\u0435\u043a)')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430 \u043a\u043e\u043c\u0430\u043d\u0434\u044b \u043d\u0430 \u0443\u0440\u043e\u0432\u043d\u0435',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430 \u043a\u043e\u043c\u0430\u043d\u0434 \u043d\u0430 \u0443\u0440\u043e\u0432\u043d\u044f\u0445',
            },
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='system.Game', verbose_name='\u0418\u0433\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='order',
            field=models.IntegerField(default=0, verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='available_in',
            field=models.IntegerField(default=0, verbose_name='\u0414\u043e\u0441\u0442\u0443\u043f\u043d\u0430 \u0447\u0435\u0440\u0435\u0437(\u043c\u0438\u043d)'),
        ),
        migrations.AddField(
            model_name='levelstat',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='system.GameLevel', verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c'),
        ),
        migrations.AddField(
            model_name='levelstat',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Team', verbose_name='\u041a\u043e\u043c\u0430\u043d\u0434\u0430'),
        ),
        migrations.AddField(
            model_name='answer',
            name='level_stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='system.LevelStat', verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u0442\u043e \u043e\u0442\u043f\u0440\u0430\u0432\u0438\u043b'),
        ),
    ]
