# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-10 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20191109_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelstat',
            options={'ordering': ['level__order'], 'verbose_name': '\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430 \u043a\u043e\u043c\u0430\u043d\u0434\u044b \u043d\u0430 \u0443\u0440\u043e\u0432\u043d\u0435', 'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430 \u043a\u043e\u043c\u0430\u043d\u0434 \u043d\u0430 \u0443\u0440\u043e\u0432\u043d\u044f\u0445'},
        ),
        migrations.AddField(
            model_name='teamingame',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='\u0417\u0430\u043a\u043e\u043d\u0447\u0438\u043b\u0438 \u0438\u0433\u0440\u0443'),
        ),
    ]
