# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-10 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20191110_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finishes_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043a\u043e\u043d\u0446\u0430'),
        ),
    ]
