# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-10 11:36
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000, verbose_name='\u041e\u0442\u0432\u0435\u0442')),
                ('right', models.BooleanField(default=False, verbose_name='\u041f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u044b\u0439')),
                ('bonus_time', models.IntegerField(default=0, verbose_name='\u0411\u043e\u043d\u0443\u0441(\u0441\u0435\u043a)')),
            ],
            options={
                'verbose_name': '\u041e\u0442\u0432\u0435\u0442',
                'verbose_name_plural': '\u041e\u0442\u0432\u0435\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0431\u043e\u043d\u0443\u0441\u0430')),
                ('content', ckeditor.fields.RichTextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0437\u0430\u0434\u0430\u043d\u0438\u044f \u0431\u043e\u043d\u0443\u0441\u0430')),
                ('bonus_time', models.IntegerField(default=0, verbose_name='\u0411\u043e\u043d\u0443\u0441\u043d\u043e\u0435 \u0432\u0440\u0435\u043c\u044f(\u043c\u0438\u043d)')),
                ('right_answers', models.TextField(verbose_name='\u041f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u044b\u0435 \u043e\u0442\u0432\u0435\u0442\u044b(json array)')),
            ],
            options={
                'ordering': ['level', 'order'],
                'verbose_name': '\u0411\u043e\u043d\u0443\u0441',
                'verbose_name_plural': '\u0411\u043e\u043d\u0443\u0441\u044b',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('content', ckeditor.fields.RichTextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('starts_at', models.DateTimeField(verbose_name='\u0412\u0440\u0435\u043c\u044f \u043d\u0430\u0447\u0430\u043b\u0430')),
                ('finishes_at', models.DateTimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043a\u043e\u043d\u0446\u0430')),
                ('finished', models.BooleanField(default=False, verbose_name='\u0417\u0430\u043a\u043e\u043d\u0447\u0435\u043d')),
                ('status', models.CharField(choices=[[b'not_started', '\u041d\u0435 \u043d\u0430\u0447\u0430\u0442'], [b'started', '\u0418\u0434\u0435\u0442'], [b'scoring', '\u041f\u043e\u0434\u0441\u0447\u0435\u0442 \u043e\u0447\u043a\u043e\u0432'], [b'finished', '\u0417\u0430\u043a\u043e\u043d\u0447\u0435\u043d']], default=b'not_started', max_length=20, verbose_name='\u0421\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435')),
                ('sequence', models.CharField(choices=[[b'linear', '\u041b\u0438\u043d\u0435\u0439\u043d\u0430\u044f'], [b'random', '\u0428\u0442\u0443\u0440\u043c\u043e\u0432\u0430\u044f']], default=b'linear', max_length=20, verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043e\u0432\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_games', to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440 \u0438\u0433\u0440\u044b')),
            ],
            options={
                'ordering': ['starts_at'],
                'verbose_name': '\u0418\u0433\u0440\u0430',
                'verbose_name_plural': '\u0418\u0433\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0443\u0440\u043e\u0432\u043d\u044f')),
                ('content', ckeditor.fields.RichTextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0437\u0430\u0434\u0430\u043d\u0438\u044f')),
                ('right_answers', models.TextField(verbose_name='\u041f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u044b\u0435 \u043e\u0442\u0432\u0435\u0442\u044b(json array)')),
                ('auto_close_time', models.IntegerField(default=0, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0430\u0432\u0442\u043e\u043f\u0435\u0440\u0435\u0445\u043e\u0434\u0430(\u043c\u0438\u043d)')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='system.Game', verbose_name='\u0418\u0433\u0440\u044b')),
            ],
            options={
                'ordering': ['game', 'order'],
                'verbose_name': '\u0423\u0440\u043e\u0432\u0435\u043d\u044c \u0438\u0433\u0440\u044b',
                'verbose_name_plural': '\u0423\u0440\u043e\u0432\u043d\u0438 \u0438\u0433\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0438')),
                ('available_in', models.IntegerField(default=0, verbose_name='\u0414\u043e\u0441\u0442\u0443\u043f\u043d\u0430 \u0447\u0435\u0440\u0435\u0437(\u043c\u0438\u043d)')),
                ('penalty', models.IntegerField(default=0, verbose_name='\u0428\u0442\u0440\u0430\u0444\u043d\u043e\u0435 \u0432\u0440\u0435\u043c\u044f(\u043c\u0438\u043d)')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.GameLevel', verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c \u0438\u0433\u0440\u044b')),
            ],
            options={
                'ordering': ['level', 'available_in'],
                'verbose_name': '\u041f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0430',
                'verbose_name_plural': '\u041f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0438\u0433\u043b\u0430\u0448\u0435\u043d\u0438\u0435 \u0432 \u043a\u043e\u043c\u0430\u043d\u0434\u0443',
                'verbose_name_plural': '\u041f\u0440\u0438\u0433\u043b\u0430\u0448\u0435\u043d\u0438\u044f \u0432 \u043a\u043e\u043c\u0430\u043d\u0434\u0443',
            },
        ),
        migrations.CreateModel(
            name='LevelStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043d\u0430\u0447\u0430\u043b\u0430 \u0443\u0440\u043e\u0432\u043d\u044f')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043a\u043e\u043d\u0446\u0430 \u0443\u0440\u043e\u0432\u043d\u044f')),
                ('time_in_level', models.IntegerField(default=0, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043d\u0430 \u0443\u0440\u043e\u0432\u043d\u0435(\u0441\u0435\u043a)')),
                ('total_penalty', models.IntegerField(default=0, verbose_name='\u0428\u0442\u0440\u0430\u0444\u043e\u0432 \u043d\u0430 \u0443\u0440\u043e\u0432\u043d\u0435(\u0441\u0435\u043a)')),
                ('total_bonus', models.IntegerField(default=0, verbose_name='\u0411\u043e\u043d\u0443\u0441\u043e\u0432 \u043d\u0430 \u0443\u0440\u043e\u0432\u043d\u0435(\u0441\u0435\u043a)')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='system.GameLevel', verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c')),
            ],
            options={
                'ordering': ['level__order'],
                'verbose_name': '\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430 \u043a\u043e\u043c\u0430\u043d\u0434\u044b \u043d\u0430 \u0443\u0440\u043e\u0432\u043d\u0435',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430 \u043a\u043e\u043c\u0430\u043d\u0434 \u043d\u0430 \u0443\u0440\u043e\u0432\u043d\u044f\u0445',
            },
        ),
        migrations.CreateModel(
            name='PlayerInGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='system.Game', verbose_name='\u0418\u0433\u0440\u0430')),
            ],
            options={
                'verbose_name': '\u0418\u0433\u0440\u043e\u043a \u0432 \u0438\u0433\u0440\u0435',
                'verbose_name_plural': '\u0418\u0433\u0440\u043e\u043a\u0438 \u0432 \u0438\u0433\u0440\u0435',
            },
        ),
        migrations.CreateModel(
            name='TeamInGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False, verbose_name='\u0417\u0430\u043a\u043e\u043d\u0447\u0438\u043b\u0438 \u0438\u0433\u0440\u0443')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='system.Game', verbose_name='\u0418\u0433\u0440\u0430')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043c\u0430\u043d\u0434\u0430 \u0432 \u0438\u0433\u0440\u0435',
                'verbose_name_plural': '\u041a\u043e\u043c\u0430\u043d\u0434\u044b \u0432 \u0438\u0433\u0440\u0435',
            },
        ),
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_teams', to=settings.AUTH_USER_MODEL, verbose_name='\u0421\u043e\u0437\u0434\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='is_cap',
            field=models.BooleanField(default=False, verbose_name='\u041a\u0430\u043f\u0438\u0442\u0430\u043d \u0441\u0432\u043e\u0435\u0439 \u043a\u043e\u043c\u0430\u043d\u0434\u044b'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sex',
            field=models.CharField(choices=[[b'male', '\u041c\u0443\u0436\u0441\u043a\u043e\u0439'], [b'female', '\u0416\u0435\u043d\u0441\u043a\u0438\u0439']], default=b'male', max_length=10, verbose_name='\u041f\u043e\u043b'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='system.Team', verbose_name='\u0422\u0435\u043a\u0443\u0449\u0430\u044f \u043a\u043e\u043c\u0430\u043d\u0434\u0430'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='teamingame',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='system.Team', verbose_name='\u041a\u043e\u043c\u0430\u043d\u0434\u0430'),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Team', verbose_name='\u0412 \u0441\u043e\u0441\u0442\u0430\u0432\u0435 \u043a\u043e\u043c\u0430\u043d\u0434\u044b'),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='\u0418\u0433\u0440\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='levelstat',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Team', verbose_name='\u041a\u043e\u043c\u0430\u043d\u0434\u0430'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='system.Team', verbose_name='\u0412 \u043a\u043e\u043c\u0430\u043d\u0434\u0443'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u043e\u0433\u043e'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.GameLevel', verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c \u0438\u0433\u0440\u044b'),
        ),
        migrations.AddField(
            model_name='answer',
            name='level_stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='system.LevelStat', verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u0442\u043e \u043e\u0442\u043f\u0440\u0430\u0432\u0438\u043b'),
        ),
    ]
